multi_camp_2021/python/django_with_form&classView/ch03/books/urls.py
from django.contrib import admin
from django.urls import path
from books.views import *

app_name ='books'

urlpatterns = [
    path('',BooksModelView.as_view(),name='index'), #books/
    path('book/',BookList.as_view(),name='book_list'), #books/book
    path('book/<int:pk>',BookDetail.as_view(),name='book_detail'), #books/book/3/

    path('author/',AuthorList.as_view(),name='author_list'), #books/author
    path('author/<int:pk>',AuthorDetail.as_view(),name='author_detail'), #books/author/3

    path('publisher/',PublisherList.as_view(),name='publisher_list'), #books/publisher
    path('publisher/<int:pk>',PublisherDetail.as_view(),name='publisher_detail'), #books/publisher/3
]

multi_camp_2021/python/django_with_form&classView/ch03/mysite/urls.py
# from ch03.polls.views import *
from django.contrib import admin
from django.urls import path,include
from polls import views
from books import views
from mysite.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    path('todos/',include('todos.urls')),
    path('books/',include('books.urls')),
    path('',HomeView.as_view(),name="home"),


]

multi_camp_2021/python/django_with_form&classView/ch03/todos/urls.py
from django.urls import path
from todos.views import *

app_name ='todos'

urlpatterns = [
    path('',IndexView.as_view(),name='index'), #todo/
    path('register',register,name='todo_register'), #todo/
    path('delete/<int:todo_id>',delete,name='todo_delete'), #todo/
    path('update/<int:todo_id>',update,name='todo_update'), #todo/
    path('detail/<int:pk>',TodoDetail.as_view(),name='todo_detail'), #todo/
    path('list',TodoList.as_view(),name='todo_list'), #todo/
]

multi_camp_2021/python/django_with_form&classView/ch03/todos/models.py
from django.db import models
from django.db.models.base import Model
# Create your models here.


class Todo(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    content = models.CharField(max_length=200)

    def __str__(self):
        return str(self.title) +" : "+str(self.content)

multi_camp_2021/python/django_with_form&classView/ch03/todos/forms.py
from django import forms
from .models import Todo


class TodoWriteForm(forms.ModelForm):
    class Meta :
        model =Todo
        fields=[
            'title',
            'content',
            'pub_date'
        ]
        

multi_camp_2021/python/django_with_form&classView/ch03/todos/views.py
from django import forms
from django.db import models
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

from django.views.generic.detail import DetailView
from .models import Todo
from .forms import TodoWriteForm
from django.http import HttpResponseRedirect


class IndexView(TemplateView):
    template_name = "todos/index.html"


class TodoDetail(DetailView):
    model = Todo


class TodoList(ListView):
    model =Todo


def update(request,todo_id):

    todo = get_object_or_404(Todo,pk=todo_id)
    
    # todo.save()
    # return render(request,'todos/index.html')
    if request.method =="POST":
        form = TodoWriteForm(request.POST)
        
        if form.is_valid():
            form.fields['pk']=todo_id
            todo.delete()
            form.save()
            return render(request,'todos/index.html')
        else:
            return render(request,'todos/index.html')
    else:
        form =TodoWriteForm()
        return render(request,'todos/todo_update.html',{'form':form})
    
    


def delete(request,todo_id):

    todo_delete = get_object_or_404(Todo,pk=todo_id)
    todo_delete.delete()
    
    return render(request,'todos/index.html')


def register(request):
    
    if request.method =="POST":
        form = TodoWriteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'todos/index.html')
        else:
            return render(request,'todos/index.html')
    else:
        form =TodoWriteForm()
        return render(request,'todos/todo_register.html',{'form':form})
    

multi_camp_2021/python/django_with_form&classView/ch03/todos/templates/todos/index.html
{% extends 'base_todos.html' %}
{% block title %}Todo_Index{%endblock  %}
{% block content %}
  <ul>
    <li><a href="{% url 'todos:todo_list' %}">일정 목록 보기</a></li>
    <li><a href="{% url 'todos:todo_register' %}">일정 등록</a></li>
  </ul>

{%endblock%}
<!-- 
<ul>
  <li><a href="/todos/lists/">일정 목록 보기</a></li>
  <li><a href="/todos/register/">일정 등록</a></li>
  <li><a href="/todos/details/">일정 상세 보기</a></li>
  <li><a href="/todos/delete/">일정 삭제</a></li>
  <li><a href="/todos/update/">일정 수정</a></li>
</ul> -->

multi_camp_2021/python/django_with_form&classView/ch03/todos/templates/todos/todo_detail.html
{% extends 'base_todos.html' %}

{% block content %}
    <h1>Todo Detail</h1>
        
        <tr>
            <td>{{object.title}}</td>
            <td>{{object.content}}</td>
            <td>{{object.pub_date}}</td>
            <td><a href="{% url 'todos:todo_delete' object.id %}"> 삭제 </a></td>
            <td><a href="{% url 'todos:todo_update' object.id %}"> 수정 </a></td>
        </tr>
        
{% endblock %}

multi_camp_2021/python/django_with_form&classView/ch03/todos/templates/todos/todo_list.html
{% extends 'base_todos.html' %}
{% block title %}Todo{%endblock  %}
{% block content %}
        <h1>Todo List</h1>
        {%if object_list %}
        <table>
            {% for todo in object_list %}
            <tr>
                <td>{{todo.title}}</td>
                
                <td><a href="{% url 'todos:todo_delete' todo.id %}"> 삭제 </a></td>
                <td><a href="{% url 'todos:todo_detail' todo.id %}"> detail </a></td>
            </tr>
               
            {% endfor %}
        </table>
        {%else%}
        <p> 일정이 없습니다.</p>
        {%endif %}
{%endblock%}

multi_camp_2021/python/django_with_form&classView/ch03/todos/templates/todos/todo_register.html
{% extends 'base_todos.html' %}
{% block title %}Todo{%endblock  %}
{% block content %}
  <form  method="POST">
      {% csrf_token%}
      {{form.as_p}}
      <input type="submit" value="저장"/>
  </form>
{%endblock%}

multi_camp_2021/python/django_with_form&classView/ch03/todos/templates/todos/todo_update.html
{% extends 'base_todos.html' %}
{% block title %}Todo{%endblock  %}
{% block content %}
        <h1>Todo Modify</h1>
        <form  method="POST">
          {% csrf_token%}
          {{form.as_p}}
          <input type="submit" value="수정"/>
        </form>
{%endblock%}