multi_camp_2021/python/django/ch03/todos/urls.py
from django.urls import path
from todos import views

app_name ='todos'

urlpatterns = [
    path('',views.index,name='index'), #todo/
    path('register',views.register,name='register'), #todo/
    path('delete/<int:todo_id>',views.delete,name='delete'), #todo/
    path('update/<int:todo_id>',views.update,name='update'), #todo/
    path('detail/<int:todo_id>',views.detail,name='detail'), #todo/
    path('lists',views.lists,name='lists'), #todo/
]

multi_camp_2021/python/django/ch03/todos/forms.py
from django import forms
from .models import Todo


class TodoWriteForm(forms.ModelForm):
    class Meta :
        model =Todo
        fields=[

            'title',
            'content',
            'pub_date'
        ]
        

multi_camp_2021/python/django/ch03/todos/views.py
from django import forms
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse
from .models import Todo
from .forms import TodoWriteForm
from django.http import HttpResponseRedirect


def index(request):
    return render(request,'todos/index.html')


def update(request,todo_id):

    todo = get_object_or_404(Todo,pk=todo_id)
    
    if request.method =="POST":
        form = TodoWriteForm(request.POST)
        
        if form.is_valid():
            form.save()

            last = Todo.objects.last()
            todo.title=last.title
            todo.content=last.content
            todo.pub_date =last.pub_date
            
            last.delete()
            todo.save()
            return render(request,'todos/index.html')
        else:
            return render(request,'todos/index.html')
    else:
        form =TodoWriteForm()
        return render(request,'todos/update.html',{'form':form})
    


def delete(request,todo_id):

    todo_delete = get_object_or_404(Todo,pk=todo_id)
    todo_delete.delete()
    
    return render(request,'todos/index.html')


def register(request):
    
    if request.method =="POST":
        form = TodoWriteForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'todos/index.html')
        else:
            return render(request,'todos/index.html')
    else:
        form =TodoWriteForm()
        return render(request,'todos/register.html',{'form':form})
    


def detail(request,todo_id):
    todo = Todo.objects.get(pk=todo_id)
    context = {'todo':todo}
    return render(request,'todos/detail.html',context)


def lists(request):
    todo_lists =Todo.objects.all().order_by("id")
    context = {"todo_lists":todo_lists}
    return render(request,'todos/lists.html',context)

multi_camp_2021/python/django/ch03/todos/templates/todos/detail.html
<!DOCTYPE html>
<html>
<head>
    <title> Todo </title>
</head>
<body>
    <div id="content">
        <h1>Todo Detail</h1>
        {% if todo %}
        <tr>
            <td>{{todo.title}}</td>
            <td>{{todo.content}}</td>
            <td>{{todo.pub_date}}</td>
            <td><a href="{% url 'todos:delete' todo.id %}"> 삭제 </a></td>
            <td><a href="{% url 'todos:update' todo.id %}"> 수정 </a></td>
        </tr>
        {%else%}
        <p>상세보기가 안됩니다.</p>
        {%endif%}
    </div>
</body>
</html>

multi_camp_2021/python/django/ch03/todos/templates/todos/index.html
<ul>
  <li><a href="{% url 'todos:lists' %}">일정 목록 보기</a></li>
  <li><a href="{% url 'todos:register' %}">일정 등록</a></li>
</ul>

<!-- 
<ul>
  <li><a href="/todos/lists/">일정 목록 보기</a></li>
  <li><a href="/todos/register/">일정 등록</a></li>
  <li><a href="/todos/details/">일정 상세 보기</a></li>
  <li><a href="/todos/delete/">일정 삭제</a></li>
  <li><a href="/todos/update/">일정 수정</a></li>
</ul> -->

multi_camp_2021/python/django/ch03/todos/templates/todos/lists.html
<!DOCTYPE html>
<html>
<head>
    <title> Todo </title>
</head>
<body>
    <div id="content">
        <h1>Todo List</h1>
        {%if todo_lists %}
        <table>
            {% for todo in todo_lists %}
            <tr>
                <td>{{todo.id}}</td>
                <td>{{todo.title}}</td>
                <td><a href="{% url 'todos:detail' todo.id %}"> details </a></td>
                <td><a href="{% url 'todos:delete' todo.id %}"> 삭제 </a></td>
            </tr>
               
            {% endfor %}
        </table>
        {%else%}
        <p> 일정이 없습니다.</p>
        {%endif %}
    </div>
</body>
</html>

multi_camp_2021/python/django/ch03/todos/templates/todos/register.html
<!DOCTYPE html>
<html>
<head>
    <title> Todo </title>
</head>
<body>
  <form  method="POST">
      {% csrf_token%}
      {{form.as_p}}
      <input type="submit" value="저장"/>
  </form>
</body>

multi_camp_2021/python/django/ch03/todos/templates/todos/update.html
<!DOCTYPE html>
<html>
<head>
    <title> Todo </title>
</head>
<body>
    <div id="content">
        <h1>Todo Modify</h1>
        <form  method="POST">
          {% csrf_token%}
          {{form.as_p}}
          <input type="submit" value="수정"/>
        </form>
    </div>
</body>
</html>